export const userData = [
    [
      {
        ID: 1,
        "First Name": "Ajay",
        "Middle Name": "",
        "Last Name": "Prajapati",
        Email: "ajay.prajapati@sourcefuse.com",
        Phone: "+917054846285",
        Role: "Super Admin",
        Address: "Lucknow, Uttar Pradesh",
      },
      {
        ID: 2,
        "First Name": "Nilesh",
        "Middle Name": "",
        "Last Name": "Kumar",
        Email: "nilesh.kumar@sourcefuse.com",
        Phone: "+916394716607",
        Role: "Admin",
        Address: "Hardoi, Uttar Pradesh",
      },
      {
        ID: 3,
        "First Name": "Shiv",
        "Middle Name": "Prakash",
        "Last Name": "Yadav",
        Email: "shiv.yadav@gmail.com",
        Phone: "+918318066761",
        Role: "Admin",
        Address: "Lucknow, Uttar Pradesh",
      },
      {
        ID: 4,
        "First Name": "Arjun",
        "Middle Name": "",
        "Last Name": "Dubey",
        Email: "arjun.dubey@gmail.com",
        Phone: "+917062391050",
        Role: "Subscriber",
        Address: "Mainpuri, Uttar Pradesh",
      },
      {
        ID: 5,
        "First Name": "Arisha",
        "Middle Name": "",
        "Last Name": "Fatima",
        Email: "arisha.fatima@gmail.com",
        Phone: "+919876534132",
        Role: "Subscriber",
        Address: "Hardoi, Uttar Pradesh",
      },
      {
        ID: 6,
        "First Name": "Saurabh",
        "Middle Name": "",
        "Last Name": "Kannaujiya",
        Email: "saurabh.kannaujiya@gmail.com",
        Phone: "+918953831639",
        Role: "Subscriber",
        Address: "Lucknow, Uttar Pradesh",
      },
      {
        ID: 7,
        "First Name": "Satyam",
        "Middle Name": "",
        "Last Name": "Singh",
        Email: "satyam.singh@gmail.com",
        Phone: "+919786354132",
        Role: "Subscriber",
        Address: "Lucknow, Uttar Pradesh",
      },
    ],
  ];