export const userData = [
    [
      {
        ID: 1,
        "First Name": "R",
        "Middle Name": "",
        "Last Name": "V",
        Email: "r.v@sourcefuse.com",
        Phone: "+91987654321",
        Role: "Super Admin",
        Address: "India",
      },
      {
        ID: 2,
        "First Name": "N",
        "Middle Name": "",
        "Last Name": "K",
        Email: "n.k@sourcefuse.com",
        Phone: "+91987654321",
        Role: "Admin",
        Address: "India",
      },
      {
        ID: 3,
        "First Name": "S",
        "Middle Name": "",
        "Last Name": "Y",
        Email: "s.y@gmail.com",
        Phone: "+910987654321",
        Role: "Admin",
        Address: "India",
      },
      {
        ID: 4,
        "First Name": "A",
        "Middle Name": "",
        "Last Name": "D",
        Email: "a.d@gmail.com",
        Phone: "+91989898989",
        Role: "Subscriber",
        Address: "India",
      },
      {
        ID: 5,
        "First Name": "A",
        "Middle Name": "",
        "Last Name": "F",
        Email: "a.f@gmail.com",
        Phone: "+91987612345",
        Role: "Subscriber",
        Address: "India",
      },
      {
        ID: 6,
        "First Name": "S",
        "Middle Name": "",
        "Last Name": "K",
        Email: "s.k@gmail.com",
        Phone: "+91969696969",
        Role: "Subscriber",
        Address: "India",
      },
      {
        ID: 7,
        "First Name": "S",
        "Middle Name": "",
        "Last Name": "S",
        Email: "s.s@gmail.com",
        Phone: "+918989898989",
        Role: "Subscriber",
        Address: "India",
      },
    ],
  ];